# Generated by Django 5.2.14 on 2026-05-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('players', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('boss_wechat', models.CharField(max_length=50)),
                ('game_id', models.CharField(blank=True, max_length=100, null=True)),
                ('addon_details', models.JSONField(blank=True, null=True)),
                ('required_players', models.IntegerField()),
                ('designated_types', models.JSONField(blank=True, null=True)),
                ('designated_players', models.JSONField(blank=True, null=True)),
                ('boss_note', models.TextField(blank=True, null=True)),
                ('total_price_per_hour', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('待接单', '待接单'), ('进行中', '进行中'), ('待支付', '待支付'), ('已完成', '已完成'), ('已取消', '已取消')], default='待接单', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('custom_price', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('booked_hours', models.FloatField(default=1.0)),
                ('timer_started_at', models.DateTimeField(blank=True, null=True)),
                ('paused_duration', models.IntegerField(default=0)),
                ('is_paused', models.BooleanField(default=False)),
                ('last_paused_at', models.DateTimeField(blank=True, null=True)),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='catalog.addon')),
                ('boss_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.package')),
                ('payment_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='orders.order')),
            ],
            options={
                'db_table': 'order_edit_logs',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='orders.order')),
            ],
            options={
                'db_table': 'order_status_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_designated', models.BooleanField(default=False)),
                ('designated_type_id', models.IntegerField(blank=True, null=True)),
                ('grab_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='已接单', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_players', to='orders.order')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_players', to='players.player')),
            ],
            options={
                'db_table': 'order_players',
                'unique_together': {('order', 'player')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='orders.order')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='players.player')),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('order', 'player')},
            },
        ),
    ]
