# Generated by GPT-5.5 Thinking on 2026-06-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id', models.CharField(blank=True, default='', max_length=80)),
                ('spec_name', models.CharField(blank=True, default='', max_length=120)),
                ('spec_display_name', models.CharField(blank=True, default='', max_length=120)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车商品',
                'verbose_name_plural': '购物车商品',
                'db_table': 'cart_items',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'package', 'spec_id')},
            },
        ),
    ]
