# Generated by Django 4.2.30 on 2026-06-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '订单', 'verbose_name_plural': '订单列表'},
        ),
        migrations.AlterModelOptions(
            name='ordereditlog',
            options={'verbose_name': '订单编辑日志', 'verbose_name_plural': '订单编辑日志列表'},
        ),
        migrations.AlterModelOptions(
            name='orderplayer',
            options={'verbose_name': '订单陪玩', 'verbose_name_plural': '订单陪玩列表'},
        ),
        migrations.AlterModelOptions(
            name='orderstatuslog',
            options={'ordering': ['-created_at'], 'verbose_name': '订单状态日志', 'verbose_name_plural': '订单状态日志列表'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': '评分', 'verbose_name_plural': '评分列表'},
        ),
        migrations.AddField(
            model_name='order',
            name='package_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='下单时商品名快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='spec_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='规格ID'),
        ),
        migrations.AddField(
            model_name='order',
            name='spec_name_snapshot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='下单时规格名快照'),
        ),
        migrations.AddField(
            model_name='order',
            name='spec_price_snapshot',
            field=models.FloatField(blank=True, null=True, verbose_name='下单时规格价快照'),
        ),
    ]
