# Generated by Django 4.2.30 on 2026-06-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_package_image_url_package_picture_url_and_more'),
        ('orders', '0002_alter_order_options_alter_ordereditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id_snapshot', models.CharField(blank=True, default='', max_length=80)),
                ('spec_name', models.CharField(blank=True, default='', max_length=120)),
                ('spec_display_name', models.CharField(blank=True, default='', max_length=120)),
                ('price', models.FloatField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.package')),
                ('spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='catalog.packagespec')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '购物车项',
                'verbose_name_plural': '购物车列表',
                'db_table': 'cart_items',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'package', 'spec_id_snapshot')},
            },
        ),
    ]
