# Generated by Django 4.2.30 on 2026-09-22 16:26

import apps.gifts.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_remove_room_entry_deadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge_no', models.CharField(max_length=64, unique=True)),
                ('amount_diamonds', apps.gifts.fields.DiamondPriceField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount_yuan', models.DecimalField(decimal_places=2, max_digits=14)),
                ('refunded_diamonds', models.PositiveBigIntegerField(default=0)),
                ('attempt_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('unknown', 'unknown'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('partially_refunded', 'partially_refunded'), ('refunded', 'refunded')], default='created', max_length=24)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surcharges', to='orders.order')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='ordersurcharge',
            constraint=models.UniqueConstraint(fields=('boss', 'idempotency_key'), name='surcharge_boss_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='ordersurcharge',
            constraint=models.CheckConstraint(check=models.Q(('amount_diamonds__gt', 0), ('amount_yuan__gt', 0)), name='surcharge_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='ordersurcharge',
            constraint=models.CheckConstraint(check=models.Q(('amount_diamonds', django.db.models.expressions.CombinedExpression(models.F('amount_yuan'), '*', models.Value(10)))), name='surcharge_yuan_diamonds'),
        ),
        migrations.AddConstraint(
            model_name='ordersurcharge',
            constraint=models.CheckConstraint(check=models.Q(('refunded_diamonds__lte', models.F('amount_diamonds'))), name='surcharge_refund_bound'),
        ),
    ]
