# Generated by Django 4.2.30 on 2026-09-22 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_walletspendattempt_walletspendaudit_and_more'),
        ('orders', '0017_ordersurcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersurcharge',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.walletspendattempt'),
        ),
        migrations.AddField(
            model_name='ordersurcharge',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
