# Generated by Django 4.2.30 on 2026-09-23 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_clientwalletledger_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0019_surcharge_concurrency_guards'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersurcharge',
            name='allocation_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64)),
                ('quote_snapshot', models.JSONField(default=dict)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='created', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.walletspendattempt')),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='checkout', to='orders.order')),
                ('surcharge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.ordersurcharge')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordercheckout',
            constraint=models.UniqueConstraint(fields=('boss', 'idempotency_key'), name='checkout_boss_key'),
        ),
        migrations.AddConstraint(
            model_name='ordercheckout',
            constraint=models.CheckConstraint(check=models.Q(('base_amount__gte', 0), ('surcharge_amount__gte', 0), ('total_amount', django.db.models.expressions.CombinedExpression(models.F('base_amount'), '+', models.F('surcharge_amount')))), name='checkout_sum_exact'),
        ),
    ]
