# Generated by Django 4.2.30 on 2026-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_surcharge_checkout_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surcharge_guarded',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
