# Generated by Django 4.2.30 on 2026-09-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_decimal_payment_amounts'),
        ('orders', '0023_surcharge_lifecycle_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckoutRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(max_length=64, unique=True)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('request_payload', models.JSONField(default=dict)),
                ('remote_status', models.CharField(default='not_required', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_refund', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='payments.refund')),
                ('checkout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='full_refund', to='orders.ordercheckout')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ordercheckoutrefund',
            constraint=models.CheckConstraint(check=models.Q(('surcharge_amount__gt', 0)), name='checkout_refund_positive'),
        ),
    ]
