# Generated by Django 4.2.30 on 2026-10-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_order_source_database_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_policy',
            # Existing orders retain the legacy settlement path, no recalculation.
            field=models.CharField(default='', editable=False, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='commission_policy',
            field=models.CharField(default='standard25-mini16-v1', editable=False, max_length=32),
        ),
        migrations.RunSQL(
            "ALTER TABLE orders ALTER COLUMN commission_policy SET DEFAULT '';",
            "ALTER TABLE orders ALTER COLUMN commission_policy DROP DEFAULT;",
        ),
        migrations.AddField(
            model_name='orderplayer',
            name='commission_rate_snapshot',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
