# Generated by Django 4.2.30 on 2026-09-29 04:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0014_player_presence_seen_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronageSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, verbose_name='目录配置启用')),
                ('purchase_enabled', models.BooleanField(default=False, editable=False, verbose_name='交易开放（本阶段锁定关闭）')),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.25'), help_text='0.25 = 25%；允许0。仅冠名与包天，不影响其他业务。', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='统一平台抽成比例')),
                ('day_price_yuan', models.DecimalField(decimal_places=2, default=Decimal('188.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='日冠价格（元）')),
                ('week_price_yuan', models.DecimalField(decimal_places=2, default=Decimal('520.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='周冠价格（元）')),
                ('month_price_yuan', models.DecimalField(decimal_places=2, default=Decimal('1314.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='月冠价格（元）')),
                ('quarter_price_yuan', models.DecimalField(decimal_places=2, default=Decimal('2888.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='季冠价格（元）')),
                ('year_price_yuan', models.DecimalField(decimal_places=2, default=Decimal('9999.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.10'))], verbose_name='年冠价格（元）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '冠名/包天统一配置',
                'verbose_name_plural': '冠名/包天统一配置',
            },
        ),
        migrations.CreateModel(
            name='PlayerPatronageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate_yuan', models.DecimalField(blank=True, decimal_places=2, help_text='不绑定商品。包天 = 时薪 × 8 × 0.85；为空时不开包天。计价不是履约计时。', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='包天计价时薪（元）')),
                ('enabled', models.BooleanField(default=True, verbose_name='包天配置启用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patronage_config', to='players.player', verbose_name='陪玩')),
            ],
            options={
                'verbose_name': '陪玩包天时薪',
                'verbose_name_plural': '陪玩包天时薪',
            },
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('id', 1)), name='patronage_config_singleton'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('purchase_enabled', False)), name='patronage_phase1_no_purchase'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 1)), name='patronage_commission_range'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('day_price_yuan__gt', 0)), name='patronage_day_positive'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('week_price_yuan__gt', 0)), name='patronage_week_positive'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('month_price_yuan__gt', 0)), name='patronage_month_positive'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('quarter_price_yuan__gt', 0)), name='patronage_quarter_positive'),
        ),
        migrations.AddConstraint(
            model_name='patronagesettings',
            constraint=models.CheckConstraint(check=models.Q(('year_price_yuan__gt', 0)), name='patronage_year_positive'),
        ),
        migrations.AddConstraint(
            model_name='playerpatronageconfig',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate_yuan__isnull', True), ('hourly_rate_yuan__gt', 0), _connector='OR'), name='patronage_hourly_positive'),
        ),
    ]
