# Generated by Django 4.2.30 on 2026-09-29 04:26

import apps.patronage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_player_presence_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patronage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatronagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_no', models.CharField(default=apps.patronage.models.purchase_number, editable=False, max_length=40, unique=True)),
                ('player_name', models.CharField(max_length=50)),
                ('package_code', models.CharField(choices=[('day', '日冠'), ('week', '周冠'), ('month', '月冠'), ('quarter', '季冠'), ('year', '年冠'), ('day_pass', '包天')], max_length=16)),
                ('package_name', models.CharField(max_length=40)),
                ('amount_yuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('platform_amount_yuan', models.DecimalField(decimal_places=6, max_digits=16)),
                ('player_amount_yuan', models.DecimalField(decimal_places=6, max_digits=16)),
                ('price_version', models.CharField(max_length=64)),
                ('config_snapshot', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('payment_status', models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('unknown', 'unknown'), ('paid', 'paid'), ('failed', 'failed')], db_index=True, default='created', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('bonus_naming_days', models.PositiveSmallIntegerField(default=0)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patronage_purchases', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patronage_purchases', to='players.player')),
            ],
            options={
                'verbose_name': '冠名/包天购买记录（只读）',
                'verbose_name_plural': '冠名/包天购买记录（只读）',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.UniqueConstraint(fields=('boss', 'idempotency_key'), name='patronage_boss_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(('payment_status__in', ['created', 'processing', 'unknown', 'paid', 'failed'])), name='patronage_payment_state'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(('amount_yuan__gt', 0), ('commission_rate__gte', 0), ('commission_rate__lte', 1)), name='patronage_purchase_amount_rate'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(('platform_amount_yuan', django.db.models.expressions.CombinedExpression(models.F('amount_yuan'), '*', models.F('commission_rate'))), ('player_amount_yuan', django.db.models.expressions.CombinedExpression(models.F('amount_yuan'), '-', models.F('platform_amount_yuan')))), name='patronage_exact_split'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('payment_status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='patronage_paid_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expires_at__isnull', True), ('starts_at__isnull', True)), models.Q(('expires_at__gt', models.F('starts_at')), ('starts_at__isnull', False)), _connector='OR'), name='patronage_purchase_interval'),
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('bonus_naming_days', 7), ('package_code', 'day_pass')), models.Q(('bonus_naming_days', 0), ('package_code__in', ['day', 'week', 'month', 'quarter', 'year'])), _connector='OR'), name='patronage_bonus_consistency'),
        ),
    ]
