# Generated by Django 4.2.30 on 2026-09-29 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patronage', '0002_patronagepurchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrownGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', '购买冠名'), ('day_pass_bonus', '包天赠送')], max_length=20)),
                ('package_name', models.CharField(max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crowns', to='patronage.patronagepurchase')),
            ],
            options={
                'verbose_name': '冠名展示权益（只读）',
                'verbose_name_plural': '冠名展示权益（只读）',
                'ordering': ('starts_at', 'id'),
                'indexes': [models.Index(fields=['starts_at', 'expires_at'], name='patronage_grant_window')],
            },
        ),
        migrations.AddConstraint(
            model_name='crowngrant',
            constraint=models.UniqueConstraint(fields=('purchase', 'source'), name='patronage_grant_source_once'),
        ),
        migrations.AddConstraint(
            model_name='crowngrant',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('starts_at'))), name='patronage_grant_interval'),
        ),
        migrations.AddConstraint(
            model_name='crowngrant',
            constraint=models.CheckConstraint(check=models.Q(('source__in', ['purchase', 'day_pass_bonus'])), name='patronage_grant_source'),
        ),
    ]
