# Generated by Django 4.2.30 on 2026-09-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronage', '0003_crowngrant_crowngrant_patronage_grant_source_once_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patronagepurchase',
            name='patronage_purchase_interval',
        ),
        migrations.AddConstraint(
            model_name='patronagepurchase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('expires_at__isnull', True), ('starts_at__isnull', True)), models.Q(('expires_at__gt', models.F('starts_at')), ('expires_at__isnull', False), ('starts_at__isnull', False)), _connector='OR'), name='patronage_purchase_interval'),
        ),
    ]
