# Generated by Django 4.2.30 on 2026-09-29 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_original_order_admission_guards'),
        ('earnings', '0009_patronage_income'),
        ('players', '0014_player_presence_seen_at'),
        ('patronage', '0005_purchase_snapshot_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronagepurchase',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patronage_purchase', to='wallet.walletspendattempt'),
        ),
        migrations.CreateModel(
            name='PatronageEarning',
            fields=[
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='earning', serialize=False, to='patronage.patronagepurchase')),
                ('amount_yuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('platform_amount_yuan', models.DecimalField(decimal_places=6, max_digits=16)),
                ('player_amount_yuan', models.DecimalField(decimal_places=6, max_digits=16)),
                ('fish_per_yuan', models.DecimalField(decimal_places=12, max_digits=24)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('debt_offset_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credited_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot', models.JSONField()),
                ('release_at', models.DateTimeField()),
                ('credit_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patronage_available_income', to='earnings.walletledger')),
                ('debt_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patronage_debt_income', to='earnings.walletledger')),
                ('payment_ledger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='wallet.clientwalletledger')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patronage_earnings', to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patronageearning',
            constraint=models.CheckConstraint(check=models.Q(('amount_yuan__gt', 0), ('commission_amount__gte', 0), ('commission_rate__gte', 0), ('commission_rate__lte', 1), ('credited_amount__gte', 0), ('debt_offset_amount__gte', 0), ('fish_per_yuan__gt', 0), ('gross_amount__gte', 0), ('net_amount__gte', 0)), name='patronage_income_positive'),
        ),
        migrations.AddConstraint(
            model_name='patronageearning',
            constraint=models.CheckConstraint(check=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('commission_amount'), '+', models.F('net_amount'))), ('net_amount', django.db.models.expressions.CombinedExpression(models.F('debt_offset_amount'), '+', models.F('credited_amount')))), name='patronage_income_conserved'),
        ),
        migrations.AddConstraint(
            model_name='patronageearning',
            constraint=models.CheckConstraint(check=models.Q(('platform_amount_yuan', django.db.models.expressions.CombinedExpression(models.F('amount_yuan'), '*', models.F('commission_rate'))), ('player_amount_yuan', django.db.models.expressions.CombinedExpression(models.F('amount_yuan'), '-', models.F('platform_amount_yuan')))), name='patronage_income_yuan_split'),
        ),
        migrations.AddConstraint(
            model_name='patronageearning',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('debt_ledger__isnull', True), ('debt_offset_amount', 0)), models.Q(('debt_ledger__isnull', False), ('debt_offset_amount__gt', 0)), _connector='OR'), models.Q(models.Q(('credit_ledger__isnull', True), ('credited_amount', 0)), models.Q(('credit_ledger__isnull', False), ('credited_amount__gt', 0)), _connector='OR')), name='patronage_income_ledger_presence'),
        ),
    ]
