# Generated by Django 4.2.30 on 2026-09-29 05:19

import apps.patronage.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.math


class Migration(migrations.Migration):

    dependencies = [
        ('patronage', '0008_income_receipt_immutable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpatronageconfig',
            name='hourly_rate_yuan',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='按0.5元步长填写。不绑定商品。包天 = 时薪 × 8 × 0.85；为空时不开包天。计价不是履约计时。', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), apps.patronage.models.validate_hourly_step], verbose_name='包天计价时薪（元）'),
        ),
        migrations.AddConstraint(
            model_name='playerpatronageconfig',
            constraint=models.CheckConstraint(check=models.Q(('hourly_rate_yuan__isnull', True), ('hourly_rate_yuan', django.db.models.expressions.CombinedExpression(django.db.models.functions.math.Floor(django.db.models.expressions.CombinedExpression(models.F('hourly_rate_yuan'), '*', models.Value(2))), '/', models.Value(Decimal('2')))), _connector='OR'), name='patronage_hourly_half_yuan'),
        ),
    ]
