# Generated by Django 4.2.30 on 2026-09-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronage', '0009_approved_hourly_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowngrant',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crowngrant',
            name='extension_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
