# Generated by Django 4.2.30 on 2026-09-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patronage', '0011_grant_snapshot_immutable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patronagesettings',
            name='patronage_phase1_no_purchase',
        ),
        migrations.AlterField(
            model_name='patronagesettings',
            name='purchase_enabled',
            field=models.BooleanField(default=False, verbose_name='交易业务开关（还需运行时总闸）'),
        ),
    ]
