# Generated by Django 4.2.30 on 2026-10-09 06:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.math


class Migration(migrations.Migration):

    dependencies = [
        # Only the existing Player FK is required; archive is a separate, unreleased feature.
        ('players', '0014_player_presence_seen_at'),
        ('patronage', '0012_purchase_gates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNamingServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_code', models.CharField(choices=[('day', '日冠'), ('week', '周冠'), ('month', '月冠'), ('quarter', '季冠'), ('year', '年冠')], max_length=16)),
                ('service_hours', models.DecimalField(decimal_places=1, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='naming_service_configs', to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playernamingserviceconfig',
            constraint=models.UniqueConstraint(fields=('player', 'package_code'), name='naming_service_player_package'),
        ),
        migrations.AddConstraint(
            model_name='playernamingserviceconfig',
            constraint=models.CheckConstraint(check=models.Q(('package_code__in', ['day', 'week', 'month', 'quarter', 'year'])), name='naming_service_package'),
        ),
        migrations.AddConstraint(
            model_name='playernamingserviceconfig',
            constraint=models.CheckConstraint(check=models.Q(('service_hours__gt', 0)), name='naming_service_positive'),
        ),
        migrations.AddConstraint(
            model_name='playernamingserviceconfig',
            constraint=models.CheckConstraint(check=models.Q(('service_hours', django.db.models.expressions.CombinedExpression(django.db.models.functions.math.Floor(django.db.models.expressions.CombinedExpression(models.F('service_hours'), '*', models.Value(2))), '/', models.Value(Decimal('2'))))), name='naming_service_half_hour'),
        ),
    ]
