# Generated by Django 5.2.14 on 2026-05-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, unique=True)),
                ('unionid', models.CharField(blank=True, default='', max_length=128)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('role', models.CharField(default='client', max_length=20)),
                ('player_status', models.CharField(choices=[('none', '未申请'), ('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_profiles',
            },
        ),
    ]
