# Generated by Django 4.2.30 on 2026-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': '客户资料', 'verbose_name_plural': '客户资料列表'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='nickname_customized',
            field=models.BooleanField(default=False, verbose_name='用户自定义昵称'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
