# Generated by Django 4.2.30 on 2026-10-08 11:37

from django.db import migrations, models
import django.db.models.deletion


def protect_events(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("""
            CREATE FUNCTION reject_vip_upgrade_mutation() RETURNS trigger AS $$
            BEGIN RAISE EXCEPTION 'VIP upgrade events are immutable' USING ERRCODE = '23514'; END;
            $$ LANGUAGE plpgsql;
            CREATE TRIGGER vip_upgrade_immutable BEFORE UPDATE OR DELETE ON vip_upgrade_events
            FOR EACH ROW EXECUTE FUNCTION reject_vip_upgrade_mutation();
        """)


def unprotect_events(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP TRIGGER vip_upgrade_immutable ON vip_upgrade_events; DROP FUNCTION reject_vip_upgrade_mutation();')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_phone_binding'),
    ]

    operations = [
        migrations.CreateModel(
            name='VipUpgradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tier_id_snapshot', models.BigIntegerField(null=True)),
                ('to_tier_id_snapshot', models.BigIntegerField()),
                ('from_tier_name', models.CharField(max_length=50)),
                ('to_tier_name', models.CharField(max_length=50)),
                ('boss_name', models.CharField(max_length=100)),
                ('boss_avatar_url', models.URLField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.clientprofile')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.bossconsumptionledger')),
            ],
            options={
                'db_table': 'vip_upgrade_events',
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.RunPython(protect_events, unprotect_events),
    ]
