# Generated by Django 4.2.30 on 2026-09-22 15:49

import apps.gifts.models
import apps.gifts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='礼物名称')),
                ('code', models.CharField(default=apps.gifts.models.generate_gift_code, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('\\A[a-z0-9_]+\\Z')], verbose_name='稳定代码')),
                ('image', models.ImageField(blank=True, upload_to='gifts/%Y/%m/', validators=[apps.gifts.validators.validate_gift_image], verbose_name='礼物图片')),
                ('price_diamonds', apps.gifts.models.DiamondPriceField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='钻石单价')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='简短描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '礼物',
                'verbose_name_plural': '礼物目录',
                'db_table': 'gifts',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gift',
            constraint=models.CheckConstraint(check=models.Q(('price_diamonds__gt', 0)), name='gift_positive_price'),
        ),
    ]
