# Generated by Django 4.2.30 on 2026-09-22 15:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0013_player_service_listing'),
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGiftConfigAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='gifts.playergiftconfig')),
            ],
        ),
        migrations.AddConstraint(
            model_name='playergiftconfig',
            constraint=models.UniqueConstraint(fields=('player', 'gift'), name='gift_unique_player_config'),
        ),
        migrations.AddConstraint(
            model_name='playergiftconfig',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='gift_valid_commission'),
        ),
        migrations.AddConstraint(
            model_name='playergiftconfig',
            constraint=models.CheckConstraint(check=models.Q(('version__gte', 1)), name='gift_config_positive_version'),
        ),
    ]
