# Generated by Django 4.2.30 on 2026-09-22 16:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0013_player_service_listing'),
        ('gifts', '0002_playergiftconfig_playergiftconfigaudit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_no', models.CharField(max_length=64, unique=True)),
                ('mode', models.CharField(choices=[('inventory', '入库'), ('direct', '直送')], default='inventory', max_length=16)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z')])),
                ('status', models.CharField(choices=[('created', 'created'), ('processing', 'processing'), ('unknown', 'unknown'), ('paid', 'paid'), ('failed', 'failed'), ('cancelled', 'cancelled'), ('partially_refunded', 'partially_refunded'), ('refunded', 'refunded')], default='created', max_length=24)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftpurchase',
            constraint=models.UniqueConstraint(fields=('buyer', 'idempotency_key'), name='gift_purchase_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='giftpurchase',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='gift_purchase_quantity'),
        ),
        migrations.AddConstraint(
            model_name='giftpurchase',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mode', 'inventory'), ('recipient__isnull', True)), models.Q(('mode', 'direct'), ('recipient__isnull', False)), _connector='OR'), name='gift_purchase_recipient_mode'),
        ),
    ]
