# Generated by Django 4.2.30 on 2026-09-22 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifts', '0003_giftpurchase_giftpurchase_gift_purchase_idempotency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftInventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('paid', '购买'), ('admin_free', '后台免费')], max_length=16)),
                ('source_reference', models.CharField(max_length=100, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining', models.PositiveIntegerField()),
                ('reserved', models.PositiveIntegerField(default=0)),
                ('cost_diamonds', models.PositiveBigIntegerField(default=0)),
                ('earnings_eligible', models.BooleanField(default=False)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', '正常'), ('frozen', '冻结'), ('revoked', '撤销')], default='active', max_length=16)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gifts.giftpurchase')),
            ],
            options={
                'permissions': [('grant_free_gift', '允许显式免费零收益发放礼物')],
            },
        ),
        migrations.CreateModel(
            name='GiftInventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('grant', 'grant'), ('purchase', 'purchase'), ('send', 'send'), ('refund', 'refund'), ('revoke', 'revoke')], max_length=16)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.CharField(max_length=300)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='gifts.giftinventorylot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftinventorylot',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0), ('remaining__lte', models.F('quantity')), ('reserved__lte', models.F('remaining'))), name='gift_lot_quantity_bounds'),
        ),
        migrations.AddConstraint(
            model_name='giftinventorylot',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchase__isnull', False), ('source', 'paid')), models.Q(('cost_diamonds', 0), ('earnings_eligible', False), ('purchase__isnull', True), ('source', 'admin_free')), _connector='OR'), name='gift_lot_source_rules'),
        ),
        migrations.AddConstraint(
            model_name='giftinventoryledger',
            constraint=models.CheckConstraint(check=models.Q(('quantity_delta', 0), _negated=True), name='gift_ledger_nonzero'),
        ),
    ]
