# Generated by Django 4.2.30 on 2026-09-22 16:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0013_player_service_listing'),
        ('gifts', '0004_giftinventorylot_giftinventoryledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_no', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('source', models.CharField(choices=[('inventory', '库存'), ('direct', '直送')], default='inventory', max_length=16)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z')])),
                ('commission_snapshot', models.JSONField()),
                ('status', models.CharField(choices=[('created', 'created'), ('delivered', 'delivered'), ('failed', 'failed'), ('reversed', 'reversed')], default='created', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='send_enabled',
            field=models.BooleanField(default=False, verbose_name='允许库存赠送（全局交易仍关闭）'),
        ),
        migrations.CreateModel(
            name='GiftTransferAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('snapshot', models.JSONField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.giftinventorylot')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='gifts.gifttransfer')),
            ],
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gift'),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gifts.giftpurchase'),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player'),
        ),
        migrations.AddField(
            model_name='gifttransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='gifttransferallocation',
            constraint=models.UniqueConstraint(fields=('transfer', 'lot'), name='gift_transfer_unique_lot'),
        ),
        migrations.AddConstraint(
            model_name='gifttransferallocation',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='gift_allocation_quantity'),
        ),
        migrations.AddConstraint(
            model_name='gifttransfer',
            constraint=models.UniqueConstraint(fields=('sender', 'idempotency_key'), name='gift_transfer_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='gifttransfer',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='gift_transfer_quantity'),
        ),
        migrations.AddConstraint(
            model_name='gifttransfer',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('purchase__isnull', False), ('source', 'direct')), models.Q(('purchase__isnull', True), ('source', 'inventory')), _connector='OR'), name='gift_transfer_source'),
        ),
    ]
