# Generated by Django 4.2.30 on 2026-09-22 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0013_player_service_listing'),
        ('gifts', '0005_gifttransfer_gift_send_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_no', models.CharField(max_length=64, unique=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('diamonds', models.PositiveBigIntegerField()),
                ('amount_yuan', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'approved'), ('processing', 'processing'), ('unknown', 'unknown'), ('completed', 'completed'), ('rejected', 'rejected'), ('manual', 'manual')], default='draft', max_length=16)),
                ('wallet_status', models.CharField(default='blocked', max_length=16)),
                ('coin_status', models.CharField(default='blocked', max_length=16)),
                ('inventory_status', models.CharField(default='blocked', max_length=16)),
                ('earning_status', models.CharField(default='blocked', max_length=16)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.giftpurchase')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gifts.gifttransfer')),
            ],
        ),
        migrations.CreateModel(
            name='GiftEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earnings_eligible', models.BooleanField(default=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withdrawing_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withdrawn_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('debt_offset_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot', models.JSONField()),
                ('release_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('frozen', 'frozen'), ('available', 'available'), ('reversed', 'reversed')], default='frozen', max_length=16)),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gifts.gifttransferallocation')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='players.player')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gifts.gifttransfer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='giftrefund',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='gift_refund_quantity'),
        ),
        migrations.AddConstraint(
            model_name='giftrefund',
            constraint=models.CheckConstraint(check=models.Q(('amount_yuan__isnull', True), ('amount_yuan__gte', 0), _connector='OR'), name='gift_refund_yuan_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='giftearning',
            constraint=models.UniqueConstraint(condition=models.Q(('allocation__isnull', True)), fields=('transfer',), name='gift_unique_direct_earning'),
        ),
        migrations.AddConstraint(
            model_name='giftearning',
            constraint=models.CheckConstraint(check=models.Q(('available_amount__gte', 0), ('commission_amount__gte', 0), ('debt_offset_amount__gte', 0), ('gross_amount__gte', 0), ('net_amount__gte', 0), ('reversed_amount__gte', 0), ('withdrawing_amount__gte', 0), ('withdrawn_amount__gte', 0)), name='gift_earning_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='giftearning',
            constraint=models.CheckConstraint(check=models.Q(('gross_amount', django.db.models.expressions.CombinedExpression(models.F('commission_amount'), '+', models.F('net_amount')))), name='gift_earning_conservation'),
        ),
        migrations.AddConstraint(
            model_name='giftearning',
            constraint=models.CheckConstraint(check=models.Q(('net_amount__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('available_amount'), '+', models.F('withdrawing_amount')), '+', models.F('withdrawn_amount')), '+', models.F('debt_offset_amount')), '+', models.F('reversed_amount')))), name='gift_earning_bucket_bounds'),
        ),
        migrations.AddConstraint(
            model_name='giftearning',
            constraint=models.CheckConstraint(check=models.Q(('earnings_eligible', True), models.Q(('commission_amount', 0), ('gross_amount', 0), ('net_amount', 0)), _connector='OR'), name='gift_free_zero_earning'),
        ),
    ]
