# Generated by Django 4.2.30 on 2026-09-22 16:22

import apps.gifts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_giftrefund_giftearning_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gift',
            name='gift_positive_price',
        ),
        migrations.AddField(
            model_name='gift',
            name='internal_enabled',
            field=models.BooleanField(default=True, verbose_name='内部配置项目启用'),
        ),
        migrations.AddField(
            model_name='gift',
            name='kind',
            field=models.CharField(choices=[('gift', '普通礼物'), ('internal_surcharge', '内部订单加价配置')], default='gift', max_length=24, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price_diamonds',
            field=apps.gifts.models.DiamondPriceField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='钻石单价'),
        ),
        migrations.AddConstraint(
            model_name='gift',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'gift'), ('price_diamonds__gt', 0), ('price_diamonds__isnull', False), models.Q(('code', 'order_surcharge'), _negated=True)), models.Q(('code', 'order_surcharge'), ('image', ''), ('is_active', False), ('kind', 'internal_surcharge'), ('price_diamonds__isnull', True), ('send_enabled', False)), _connector='OR'), name='gift_kind_catalog_rules'),
        ),
    ]
