# Generated by Django 4.2.30 on 2026-09-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_walletspendattempt_walletspendaudit_and_more'),
        ('gifts', '0007_remove_gift_gift_positive_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftpurchase',
            name='attempt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.walletspendattempt'),
        ),
    ]
