# Generated by Django 4.2.30 on 2026-09-23 16:53

import apps.gifts.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0008_giftpurchase_attempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gift',
            name='gift_kind_catalog_rules',
        ),
        migrations.AlterField(
            model_name='gift',
            name='price_diamonds',
            field=apps.gifts.fields.DiamondPriceField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='钻石单价'),
        ),
        migrations.AddConstraint(
            model_name='gift',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('kind', 'gift'), ('price_diamonds__gte', 0), ('price_diamonds__isnull', False), models.Q(('code', 'order_surcharge'), _negated=True)), models.Q(('code', 'order_surcharge'), ('image', ''), ('is_active', False), ('kind', 'internal_surcharge'), ('price_diamonds__isnull', True), ('send_enabled', False)), _connector='OR'), name='gift_kind_catalog_rules'),
        ),
    ]
