# Generated by Django 5.2.14 on 2026-05-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝'), ('disabled', '已禁用')], default='approved', max_length=20)),
                ('contact_wechat', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('session_token', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='players', to='catalog.playertype')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='PlayerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_wechat', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', '审核中'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('reject_reason', models.CharField(blank=True, default='', max_length=300)),
                ('remark', models.CharField(blank=True, default='', max_length=300)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_player_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
