# Generated by Django 4.2.30 on 2026-07-11 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_playerapplication_real_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': '陪玩师', 'verbose_name_plural': '陪玩师列表'},
        ),
        migrations.AlterModelOptions(
            name='playerapplication',
            options={'ordering': ['-submitted_at'], 'verbose_name': '陪玩师申请', 'verbose_name_plural': '陪玩师申请列表'},
        ),
    ]
