# Generated by Django 4.2.30 on 2026-10-02 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def compatibility_defaults(apps, schema_editor):
    # Old code and historical migration models omit these additive columns.
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE players ALTER COLUMN archive_reason SET DEFAULT ''")
        schema_editor.execute("ALTER TABLE players ALTER COLUMN archived_name SET DEFAULT ''")
        schema_editor.execute("ALTER TABLE players ALTER COLUMN is_archived SET DEFAULT false")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0014_player_presence_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='archive_reason',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='player',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='archived_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='已移除'),
        ),
        migrations.CreateModel(
            name='PlayerArchiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=16)),
                ('reason', models.TextField()),
                ('player_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_events', to='players.player')),
            ],
        ),
        migrations.RunPython(compatibility_defaults, migrations.RunPython.noop),
    ]
