# Generated by Django 4.2.30 on 2026-09-26 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0025_surcharge_source_immutability'),
        ('dispatch', '0001_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField(editable=False, unique=True)),
                ('request_digest', models.CharField(editable=False, max_length=64)),
                ('received_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('receipt_note', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_receipt', to='orders.order')),
            ],
            options={
                'verbose_name': '线下收款派单记录',
                'verbose_name_plural': '线下收款派单记录',
            },
        ),
    ]
