# Generated by Django 4.2.30 on 2026-09-26 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch', '0002_dispatchreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_number', models.PositiveBigIntegerField()),
                ('message', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', '待核实'), ('approved', '已认领'), ('rejected', '未通过')], default='pending', max_length=12)),
                ('review_note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_claims', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dispatch.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_history_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '历史订单认领申请',
                'verbose_name_plural': '历史订单认领申请',
            },
        ),
        migrations.AddConstraint(
            model_name='historyclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('applicant', 'requested_number'), name='dispatch_pending_claim_unique'),
        ),
    ]
