# Generated by Django 4.2.30 on 2026-09-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_historyclaim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window', models.BigIntegerField(db_index=True)),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
