# Generated by Django 4.2.30 on 2026-09-23 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_surcharge_creation_admission_guards'),
        ('earnings', '0006_withdrawal_payout_batches'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playerearning',
            name='uniq_order_player_earning',
        ),
        migrations.AddField(
            model_name='playerearning',
            name='source',
            field=models.CharField(choices=[('order', '原单工资'), ('surcharge', '整单加价')], default='order', max_length=20),
        ),
        migrations.AddField(
            model_name='playerearning',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='playerearning',
            name='surcharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='orders.ordersurcharge'),
        ),
        migrations.AddConstraint(
            model_name='playerearning',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'order')), fields=('order', 'player'), name='uniq_base_order_player_earning'),
        ),
        migrations.AddConstraint(
            model_name='playerearning',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'surcharge')), fields=('surcharge', 'player'), name='uniq_surcharge_player_earning'),
        ),
        migrations.AddConstraint(
            model_name='playerearning',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('source', 'order'), ('surcharge__isnull', True)), models.Q(('source', 'surcharge'), ('surcharge__isnull', False)), _connector='OR'), name='earning_source_consistent'),
        ),
    ]
