# Generated by Django 4.2.30 on 2026-09-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0007_surcharge_income_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletledger',
            name='entry_type',
            field=models.CharField(choices=[('earning_created', '工资进入审核'), ('earning_released', '工资审核通过'), ('earning_adjusted', '工资金额调整'), ('earning_reversed', '工资冲销'), ('withdrawal_frozen', '提现冻结'), ('withdrawal_refunded', '提现退回'), ('withdrawal_paid', '提现完成'), ('admin_adjustment', '管理员调整'), ('gift_income', '礼物收益')], db_index=True, max_length=40),
        ),
    ]
