const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require(process.env.DISPATCH_JSDOM);
const cfg=JSON.parse(fs.readFileSync(0,'utf8'));
(async()=>{
  const jar=new (require(process.env.DISPATCH_JSDOM).CookieJar)();
  jar.setCookieSync('sessionid='+cfg.session+'; Path=/',cfg.base);
  async function request(url,options={}){
    const target=new URL(url,cfg.base);assert.equal(target.origin,cfg.base);
    const headers={...options.headers};if(!headers.Authorization)headers.Cookie=jar.getCookieStringSync(cfg.base);
    const response=await fetch(target,{...options,headers});
    for(const cookie of response.headers.getSetCookie())jar.setCookieSync(cookie,cfg.base);
    return response;
  }
  const initial=await request('/dispatch/');assert.equal(initial.status,200);
  const dom=new JSDOM(await initial.text(),{url:cfg.base+'/dispatch/',runScripts:'outside-only',cookieJar:jar});
  const w=dom.window,d=w.document,$=id=>d.getElementById(id);
  w.fetch=request;w.AbortController=global.AbortController;w.confirm=()=>true;
  // jsdom has no native dialog implementation; this probe checks DOM + API, not pixels.
  w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
  w.HTMLDialogElement.prototype.close=function(){this.open=false};
  await new Promise(resolve=>{if(d.readyState==='complete')resolve();else w.addEventListener('load',resolve,{once:true})});
  w.eval(fs.readFileSync(path.join(__dirname,'../static/dispatch/console.js'),'utf8'));
  d.dispatchEvent(new w.Event('DOMContentLoaded'));
  const wait=async(predicate,label)=>{for(let i=0;i<100;i++){if(predicate())return;await new Promise(r=>setTimeout(r,30))}throw new Error(label+': '+$('notice').textContent)};
  const input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('input',{bubbles:true}))};
  await wait(()=>$('package').options.length===2,'catalog');
  $('show-new').click();input('new-name','DOM老板 <b>样例</b>');input('new-note','DOM内部核实备注');$('save-customer').click();
  await wait(()=>!$('selected-customer').hidden,'new customer');
  assert.equal($('selected-customer').querySelector('b'),null,'nickname must be text');
  const id=Number($('selected-customer').textContent.match(/客户编号 (\d+)/)[1]);
  $('package').value=$('package').options[1].value;$('package').dispatchEvent(new w.Event('change'));
  input('hours','2');input('game-id','DOM房间');$('quote').click();
  await wait(()=>$('amount').textContent==='¥40.00','quote');
  input('receipt-note','隔离测试收款记录');$('received').checked=true;$('received').dispatchEvent(new w.Event('input'));
  assert.equal($('publish').disabled,false);$('publish').click();$('publish').click();
  await wait(()=>$('notice').textContent.includes('派单成功'),'publish');
  assert.equal($('publish').disabled,true);assert.equal($('pending').hidden,true);
  const no=$('notice').textContent.match(/派单成功：([^\s]+)/)[1];
  d.querySelector('[data-tab=orders]').click();await wait(()=>$('order-rows').textContent.includes(no),'list');
  $('order-rows').querySelector('button').click();await wait(()=>$('detail-dialog').open,'detail');
  assert.ok($('detail-content').textContent.includes('线下已收款'));$('close-detail').click();
  const auth={Authorization:'Bearer '+cfg.jwt,'Content-Type':'application/json'};
  const claim=await request('/api/client/history-claims/',{method:'POST',headers:auth,body:JSON.stringify({customer_id:id,message:'DOM本人申请'})});
  assert.equal(claim.status,201);assert.ok(!(await claim.text()).includes('DOM内部核实备注'));
  d.querySelector('[data-tab=claims]').click();await wait(()=>$('claim-rows').querySelector('textarea'),'claim list');
  $('claim-rows').querySelector('textarea').value='隔离场景已核实本人';$('claim-rows').querySelector('input').checked=true;
  $('claim-rows').querySelector('button.primary').click();await wait(()=>$('notice').textContent==='认领申请已处理','review');
  const history=await request('/api/boss/orders/me',{headers:auth});assert.equal(history.status,200);
  const text=await history.text();assert.ok(text.includes(no));assert.ok(!text.includes('DOM内部核实备注'));assert.ok(!text.includes('隔离测试收款记录'));
  d.querySelector('[data-tab=orders]').click();await wait(()=>$('order-rows').textContent.includes(no),'cancel list');
  $('order-rows').querySelector('button').click();await wait(()=>$('detail-dialog').open,'cancel detail');
  assert.ok($('cancel-dispatch'),'staff cancellation button');
  assert.equal($('cancel-dispatch').disabled,false);
  $('cancel-dispatch').click();await wait(()=>$('cancel-feedback').textContent.includes('取消原因'),'required reason');
  input('cancel-reason','DOM老板临时取消 <script>测试</script>');
  w.confirm=()=>false;$('cancel-dispatch').click();await new Promise(r=>setTimeout(r,50));
  assert.equal($('cancel-dispatch').disabled,false,'declined confirmation has no effect');
  w.confirm=()=>true;
  const actualFetch=w.fetch;let lost=false;
  w.fetch=async(url,options)=>{const response=await actualFetch(url,options);if(!lost&&String(url).endsWith('/cancel/')&&options.method==='POST'){lost=true;throw new Error('fixture lost committed response')}return response};
  $('cancel-dispatch').click();$('cancel-dispatch').click();
  await wait(()=>$('notice').textContent.includes('已取消派单'),'cancel readback');
  await wait(()=>$('cancel-dispatch')&&$('cancel-dispatch').disabled&&$('detail-content').textContent.includes('线下退款未确认'),'cancelled detail readback');
  await wait(()=>$('order-rows').textContent.includes('已取消'),'cancelled list readback');
  assert.ok($('detail-content').textContent.includes('线下退款未确认'));
  assert.ok($('detail-content').textContent.includes('DOM老板临时取消'));
  assert.equal($('detail-content').querySelector('script'),null,'reason must be plain text');
  assert.ok($('order-rows').textContent.includes('已取消'));
  const cancelledHistory=await request('/api/boss/orders/me',{headers:auth});
  assert.ok((await cancelledHistory.text()).includes('已取消'));
  dom.window.close();console.log('PASS: DOM + real HTTP: create → JWT claim → review → cancel reason/confirmation → lost-response readback → cancelled history; no wallet/payment writes');
})().catch(error=>{console.error(error.stack);process.exitCode=1});
