# Generated by Django 5.2.14 on 2026-05-30 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('channel', models.CharField(max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('verify_result', models.BooleanField(default=False)),
                ('handled_result', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_notify_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(db_index=True, max_length=40, unique=True)),
                ('channel', models.CharField(max_length=20)),
                ('scene', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('status', models.CharField(default='created', max_length=20)),
                ('third_trade_no', models.CharField(blank=True, max_length=80, null=True)),
                ('third_order_no', models.CharField(blank=True, max_length=80, null=True)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('notify_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(db_column='order_no', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', to_field='order_no')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
