# Generated by Django 4.2.30 on 2026-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_virtualproductbinding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': '支付记录', 'verbose_name_plural': '支付记录列表'},
        ),
        migrations.AlterModelOptions(
            name='paymentcallbacklog',
            options={'ordering': ['-created_at'], 'verbose_name': '支付回调日志', 'verbose_name_plural': '支付回调日志列表'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
