# Generated by Django 4.2.30 on 2026-09-18 14:41

import apps.support.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0016_remove_room_entry_deadlines'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=apps.support.models.complaint_number, editable=False, max_length=34, unique=True)),
                ('category', models.CharField(choices=[('service', 'service'), ('fee', 'fee'), ('account', 'account'), ('other', 'other')], max_length=20)),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, default='', max_length=100)),
                ('client_request_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('awaiting_user', 'awaiting_user'), ('resolved', 'resolved'), ('closed', 'closed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('user', 'client_request_id'), name='unique_complaint_request'),
        ),
    ]
