# Generated by Django 4.2.30 on 2026-07-26 13:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_vip_kook_room'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='余额(元)')),
                ('recharged_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='累计充值(元)')),
                ('spent_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='累计余额消费(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='accounts.clientprofile', verbose_name='老板')),
            ],
            options={
                'verbose_name': '老板钱包',
                'verbose_name_plural': '老板钱包',
                'db_table': 'client_wallets',
            },
        ),
        migrations.CreateModel(
            name='RechargeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额(元)')),
                ('product_id', models.CharField(help_text='例如 recharge_30。必须与微信虚拟支付后台中的道具ID完全一致。', max_length=20, unique=True, verbose_name='微信道具ID')),
                ('goods_price_fen', models.PositiveIntegerField(help_text='例如30元填写3000。', verbose_name='道具单价（分）')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '充值档位',
                'verbose_name_plural': '充值档位',
                'db_table': 'wallet_recharge_products',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_no', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='充值单号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='充值金额(元)')),
                ('channel', models.CharField(choices=[('wechat_virtual', '微信虚拟支付'), ('mock', '模拟支付')], default='wechat_virtual', max_length=20)),
                ('status', models.CharField(choices=[('created', '已创建'), ('paying', '支付中'), ('paid', '已支付'), ('credited', '已入账'), ('closed', '已关闭'), ('failed', '已失败')], db_index=True, default='created', max_length=20)),
                ('third_trade_no', models.CharField(blank=True, default='', max_length=80)),
                ('notify_payload', models.JSONField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('credited_at', models.DateTimeField(blank=True, null=True, verbose_name='入账时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recharge_orders', to='wallet.rechargeproduct', verbose_name='充值档位')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharge_orders', to='accounts.clientprofile', verbose_name='老板')),
            ],
            options={
                'verbose_name': '充值单',
                'verbose_name_plural': '充值单',
                'db_table': 'wallet_recharge_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientWalletLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('recharge', '充值'), ('order_payment', '订单支付'), ('refund_in', '退款入账'), ('admin_adjust', '人工调整')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动金额(元)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动后余额(元)')),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('reference_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_wallet_ledger_operations', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='wallet.clientwallet')),
            ],
            options={
                'verbose_name': '老板钱包流水',
                'verbose_name_plural': '老板钱包流水',
                'db_table': 'client_wallet_ledgers',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rechargeorder',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', Decimal('0.00'))), name='wallet_recharge_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='clientwalletledger',
            constraint=models.CheckConstraint(check=models.Q(('amount', Decimal('0.00')), _negated=True), name='client_wallet_ledger_amount_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='clientwalletledger',
            constraint=models.CheckConstraint(check=models.Q(('balance_after__gte', Decimal('0.00'))), name='client_wallet_ledger_balance_after_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientwalletledger',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_id', ''), _negated=True), fields=('wallet', 'entry_type', 'reference_id'), name='uniq_client_wallet_ledger_reference'),
        ),
        migrations.AddConstraint(
            model_name='clientwallet',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', Decimal('0.00')), ('recharged_total__gte', Decimal('0.00')), ('spent_total__gte', Decimal('0.00'))), name='client_wallet_balances_non_negative'),
        ),
    ]
