# Generated by Django 4.2.30 on 2026-09-22 16:54

import apps.wallet.spend_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_rechargeorder_checkout_order_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletSpendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('business_no', models.CharField(max_length=64)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_digest', models.CharField(max_length=64)),
                ('external_id', models.CharField(default=apps.wallet.spend_models.external_spend_id, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reserved_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_snapshot', models.JSONField(default=dict)),
                ('request_payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='prepared', max_length=16)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('blocker', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.clientwallet')),
            ],
        ),
        migrations.CreateModel(
            name='WalletSpendAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='wallet.walletspendattempt')),
            ],
        ),
        migrations.AddConstraint(
            model_name='walletspendattempt',
            constraint=models.UniqueConstraint(fields=('wallet', 'kind', 'idempotency_key'), name='wallet_spend_key'),
        ),
        migrations.AddConstraint(
            model_name='walletspendattempt',
            constraint=models.UniqueConstraint(fields=('kind', 'business_no'), name='wallet_spend_business'),
        ),
        migrations.AddConstraint(
            model_name='walletspendattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('prepared', 'dispatching', 'unknown', 'succeeded'))), fields=('wallet',), name='wallet_one_active_spend'),
        ),
        migrations.AddConstraint(
            model_name='walletspendattempt',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='wallet_spend_positive'),
        ),
        migrations.AddConstraint(
            model_name='walletspendattempt',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('reserved_amount', models.F('amount')), ('status__in', ('prepared', 'dispatching', 'unknown', 'succeeded'))), models.Q(('reserved_amount', 0), ('status__in', ('completed', 'failed'))), _connector='OR'), name='wallet_spend_reservation_state'),
        ),
    ]
