# Generated by Django 4.2.30 on 2026-09-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_surcharge_creation_admission_guards'),
        ('wallet', '0012_alter_clientwalletledger_entry_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWalletSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.JSONField(default=dict)),
                ('blocker', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.walletspendattempt')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_spend', to='orders.order')),
            ],
        ),
    ]
