# Generated by Django 4.2.30 on 2026-09-20 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0013_player_service_listing'),
        ('orders', '0016_remove_room_entry_deadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='KookAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('request_id', models.CharField(blank=True, max_length=80)),
                ('result', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KookBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_key', models.CharField(max_length=80)),
                ('kook_user_id', models.CharField(max_length=80)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('version', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KookBindingChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_key', models.CharField(max_length=80)),
                ('purpose', models.CharField(max_length=10)),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(default='pending', max_length=30)),
                ('candidate_kook_user_id', models.CharField(blank=True, max_length=80)),
                ('kook_display_name', models.CharField(blank=True, max_length=100)),
                ('proof_event_id', models.CharField(blank=True, max_length=150)),
                ('confirmation_nonce_digest', models.CharField(blank=True, max_length=64)),
                ('consumed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(default='create', max_length=10)),
                ('scope', models.CharField(max_length=10)),
                ('target_id', models.CharField(max_length=80)),
                ('binding_version', models.UUIDField(null=True)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('remote_message_id', models.CharField(blank=True, max_length=100)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('sent_at', models.DateTimeField(null=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'permissions': [('send_kook_test', 'Send fixed KOOK test notification')],
            },
        ),
        migrations.CreateModel(
            name='KookEntryIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('scope', models.CharField(max_length=10)),
                ('order_id', models.PositiveBigIntegerField()),
                ('designation_id', models.PositiveBigIntegerField(null=True)),
                ('binding_version', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(null=True)),
                ('url_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KookInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_key', models.CharField(max_length=80)),
                ('event_key', models.CharField(max_length=160)),
                ('sn', models.PositiveIntegerField(default=0)),
                ('event_time', models.BigIntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='KookMessageProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_key', models.CharField(max_length=80)),
                ('scope', models.CharField(max_length=10)),
                ('target_id', models.CharField(max_length=80)),
                ('order_id', models.PositiveBigIntegerField(default=0)),
                ('designation_key', models.CharField(default='', max_length=80)),
                ('public_epoch', models.PositiveIntegerField(default=0)),
                ('remote_message_id', models.CharField(blank=True, max_length=100)),
                ('applied_revision', models.PositiveIntegerField(default=0)),
                ('desired_revision', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='new', max_length=20)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KookOutboxEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('event_type', models.CharField(max_length=40)),
                ('order_id', models.PositiveBigIntegerField(null=True)),
                ('designation_id', models.PositiveBigIntegerField(null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('payload', models.JSONField(default=dict)),
                ('source_key', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KookOrderProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('canonical_state_hash', models.CharField(blank=True, max_length=64)),
                ('public_epoch', models.PositiveIntegerField(default=0)),
                ('latest_safe_snapshot', models.JSONField(default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.AddConstraint(
            model_name='kookmessageprojection',
            constraint=models.UniqueConstraint(fields=('bot_key', 'scope', 'target_id', 'order_id', 'designation_key', 'public_epoch'), name='kook_unique_message_stream'),
        ),
        migrations.AddConstraint(
            model_name='kookinboundevent',
            constraint=models.UniqueConstraint(fields=('bot_key', 'event_key'), name='kook_inbound_unique'),
        ),
        migrations.AddField(
            model_name='kookentryintent',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kook_integration.kookbinding'),
        ),
        migrations.AddField(
            model_name='kookdelivery',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kook_integration.kookbinding'),
        ),
        migrations.AddField(
            model_name='kookdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kook_integration.kookoutboxevent'),
        ),
        migrations.AddField(
            model_name='kookdelivery',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kook_integration.kookmessageprojection'),
        ),
        migrations.AddField(
            model_name='kookbindingchallenge',
            name='binding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kook_integration.kookbinding'),
        ),
        migrations.AddField(
            model_name='kookbindingchallenge',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='kookbinding',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddConstraint(
            model_name='kookdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'scope', 'target_id', 'operation'), name='kook_unique_delivery'),
        ),
        migrations.AddConstraint(
            model_name='kookbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('bot_key', 'player'), name='kook_active_player'),
        ),
        migrations.AddConstraint(
            model_name='kookbinding',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('bot_key', 'kook_user_id'), name='kook_active_user'),
        ),
    ]
