# Generated by Django 4.2.30 on 2026-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kook_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KookRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_key', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=64)),
                ('blocked_until', models.DateTimeField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='kookratelimit',
            constraint=models.UniqueConstraint(fields=('bot_key', 'key'), name='kook_unique_rate_gate'),
        ),
    ]
