# Generated by Django 4.2.30 on 2026-06-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'ordering': ['priority', 'id'], 'verbose_name': '加价项目', 'verbose_name_plural': '加价项目列表'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '商品', 'verbose_name_plural': '商品列表'},
        ),
        migrations.AlterModelOptions(
            name='packagegroup',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '套餐分组', 'verbose_name_plural': '套餐分组列表'},
        ),
        migrations.AlterModelOptions(
            name='playertype',
            options={'ordering': ['priority', 'id'], 'verbose_name': '陪玩类型', 'verbose_name_plural': '陪玩类型列表'},
        ),
        migrations.AddField(
            model_name='package',
            name='cover_url',
            field=models.TextField(blank=True, null=True, verbose_name='封面图URL'),
        ),
        migrations.AddField(
            model_name='package',
            name='detail_images',
            field=models.JSONField(blank=True, null=True, verbose_name='图文详情长图列表'),
        ),
        migrations.AddField(
            model_name='package',
            name='detail_text',
            field=models.TextField(blank=True, null=True, verbose_name='图文详情文字'),
        ),
        migrations.AddField(
            model_name='package',
            name='gallery_images',
            field=models.JSONField(blank=True, null=True, verbose_name='轮播图列表'),
        ),
        migrations.AddField(
            model_name='package',
            name='original_price',
            field=models.FloatField(blank=True, null=True, verbose_name='划线价'),
        ),
        migrations.AddField(
            model_name='package',
            name='product_type',
            field=models.CharField(choices=[('normal', '普通商品'), ('guarantee', '保底单'), ('fun', '趣味单'), ('special', '特色单')], default='normal', max_length=20, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='package',
            name='rules_text',
            field=models.TextField(blank=True, null=True, verbose_name='规则/玩法说明'),
        ),
        migrations.AddField(
            model_name='package',
            name='sold_count',
            field=models.IntegerField(default=0, verbose_name='已售数量'),
        ),
        migrations.AddField(
            model_name='package',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='package',
            name='base_price',
            field=models.FloatField(verbose_name='基础价'),
        ),
        migrations.AlterField(
            model_name='package',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='package',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='catalog.packagegroup', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_custom',
            field=models.BooleanField(default=False, verbose_name='是否自定义'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='package',
            name='player_count',
            field=models.IntegerField(default=1, verbose_name='默认人数'),
        ),
        migrations.CreateModel(
            name='PackageSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规格名称')),
                ('price', models.FloatField(verbose_name='规格价格')),
                ('original_price', models.FloatField(blank=True, null=True, verbose_name='规格划线价')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='规格说明')),
                ('guarantee_amount', models.CharField(blank=True, max_length=50, null=True, verbose_name='保底金额')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='catalog.package', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格列表',
                'db_table': 'package_specs',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
