# Generated by Django 4.2.30 on 2026-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_addon_options_alter_package_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='商品图URL'),
        ),
        migrations.AddField(
            model_name='package',
            name='picture_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='展示图URL'),
        ),
        migrations.AddField(
            model_name='package',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='缩略图URL'),
        ),
        migrations.AddField(
            model_name='packagespec',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='规格展示名'),
        ),
        migrations.AddField(
            model_name='packagespec',
            name='short_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='规格简称'),
        ),
        migrations.AlterField(
            model_name='package',
            name='cover_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图URL'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='商品简介'),
        ),
        migrations.AlterField(
            model_name='package',
            name='detail_images',
            field=models.JSONField(blank=True, default=list, verbose_name='图文详情长图列表'),
        ),
        migrations.AlterField(
            model_name='package',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, verbose_name='轮播图列表'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=80, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='package',
            name='product_type',
            field=models.CharField(choices=[('normal', '普通商品'), ('guarantee', '保底单'), ('fun', '趣味单'), ('special', '特色单')], default='normal', max_length=30, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='packagespec',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='规格说明'),
        ),
        migrations.AlterField(
            model_name='packagespec',
            name='name',
            field=models.CharField(max_length=120, verbose_name='规格名称'),
        ),
    ]
