# Generated by Django 5.2.14 on 2026-05-30 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('message_type', models.CharField(default='text', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='orders.order')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KeywordAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'keyword_alerts',
            },
        ),
        migrations.CreateModel(
            name='KeywordAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='', max_length=50)),
                ('matched_keyword', models.CharField(blank=True, default='', max_length=100)),
                ('content_snippet', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_handled', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.keywordalert')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_alert_logs', to='orders.order')),
            ],
            options={
                'db_table': 'keyword_alert_logs',
            },
        ),
        migrations.CreateModel(
            name='ChatReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_type', models.CharField(max_length=10)),
                ('reader_id', models.CharField(max_length=50)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_statuses', to='orders.order')),
            ],
            options={
                'db_table': 'chat_read_status',
                'unique_together': {('order', 'reader_type', 'reader_id')},
            },
        ),
    ]
