# Generated by Django 4.2.30 on 2026-07-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': '聊天消息', 'verbose_name_plural': '聊天消息列表'},
        ),
        migrations.AlterModelOptions(
            name='chatreadstatus',
            options={'verbose_name': '聊天阅读状态', 'verbose_name_plural': '聊天阅读状态列表'},
        ),
        migrations.AlterModelOptions(
            name='keywordalert',
            options={'verbose_name': '关键词告警', 'verbose_name_plural': '关键词告警列表'},
        ),
        migrations.AlterModelOptions(
            name='keywordalertlog',
            options={'verbose_name': '关键词告警日志', 'verbose_name_plural': '关键词告警日志列表'},
        ),
        migrations.AlterField(
            model_name='chatreadstatus',
            name='last_read_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
